CREATE TABLE IF NOT EXISTS `GITHUB_USERS` (
  `GITHUB_ID` bigint PRIMARY KEY,
  `USERNAME` varchar(255) UNIQUE NOT NULL,
  `PROFILE_IMAGE_URL` varchar(255),
  `ACCESS_TOKEN` text NOT NULL,
  `REFRESH_TOKEN` text,
  `TOKEN_EXPIRES_AT` datetime,
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `REPOSITORIES` (
  `REPOSITORY_ID` bigint PRIMARY KEY,
  `GITHUB_ID` bigint NOT NULL,
  `OWNER_NAME` varchar(255) NOT NULL,
  `REPOSITORY_NAME` varchar(255) NOT NULL,
  `DEFAULT_BRANCH` varchar(255) NOT NULL,
  `REPOSITORY_URL` varchar(255) NOT NULL,
  `IS_PRIVATE` boolean NOT NULL,
  `LAST_SYNCED_AT` datetime,
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime,
  
  UNIQUE KEY `REPOSITORIES_index_0` (`GITHUB_ID`, `OWNER_NAME`, `REPOSITORY_NAME`)
);

CREATE TABLE IF NOT EXISTS `ANALYSIS_REQUESTS` (
  `ANALYSIS_REQUEST_ID` bigint PRIMARY KEY,
  `REPOSITORY_ID` bigint NOT NULL,
  `BRANCH_NAME` varchar(255) NOT NULL,
  `TARGET_PATH` varchar(255) NOT NULL,
  `STATUS` varchar(255) NOT NULL COMMENT 'PENDING, RUNNING, COMPLETE, FAIL',
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `ANALYSIS_RESULTS` (
  `ANALYSIS_RESULT_ID` bigint PRIMARY KEY,
  `ANALYSIS_REQUEST_ID` bigint UNIQUE NOT NULL,
  `SUMMARY` text NOT NULL,
  `OVERALL_SCORE` int NOT NULL,
  `PASS_COUNT` int NOT NULL,
  `FAIL_COUNT` int NOT NULL,
  `NA_COUNT` int NOT NULL,
  `CREATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `ANALYSIS_ISSUES` (
  `ANALYSIS_ISSUE_ID` bigint PRIMARY KEY,
  `ANALYSIS_RESULT_ID` bigint NOT NULL,
  `ISSUE_TYPE` varchar(255) NOT NULL,
  `LEVEL_TYPE` varchar(255) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `DESCRIPTION` text NOT NULL,
  `SUGGESTION` text NOT NULL,
  `STATUS` varchar(255) NOT NULL COMMENT 'OPEN, PROGRESS, COMPLETE, IGNORE',
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `ANALYSIS_ISSUES_LOCATIONS` (
  `ANALYSIS_ISSUE_LOCATION_ID` bigint PRIMARY KEY,
  `ANALYSIS_ISSUE_ID` bigint NOT NULL,
  `TARGET_FILE_PATH` varchar(255) NOT NULL,
  `ORIGINAL_CODE_BLOCK` text NOT NULL,
  `CSS_SELECTOR` varchar(255),
  `COMPONENT_NAME` varchar(255),
  `STATUS` varchar(255) NOT NULL COMMENT 'OPEN, MODIFY, COMPLETE',
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `CHAT_MESSAGES` (
  `CHAT_MESSAGE_ID` bigint PRIMARY KEY,
  `ANALYSIS_REQUEST_ID` bigint NOT NULL,
  `SENDER_TYPE` varchar(255) NOT NULL COMMENT 'USER, AI, SYSTEM',
  `CONTENT` text NOT NULL,
  `CREATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `CHAT_CONTEXTS` (
  `CHAT_CONTEXT_ID` bigint PRIMARY KEY,
  `ANALYSIS_REQUEST_ID` bigint UNIQUE NOT NULL,
  `CURRENT_ANALYSIS_ISSUE_LOCATION_ID` bigint,
  `REPOSITORY_CONTEXT` text,
  `USER_PREFERENCE` text,
  `RESPONSE_GUIDE` text,
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `PUSH_HISTORIES` (
  `PUSH_HISTORY_ID` bigint PRIMARY KEY,
  `REPOSITORY_ID` bigint NOT NULL,
  `PUSHED_BRANCH` varchar(255) NOT NULL,
  `STATUS` varchar(255) NOT NULL COMMENT 'SUCCESS, FAIL',
  `ERROR_MESSAGE` text,
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

CREATE TABLE IF NOT EXISTS `COMMIT_HISTORIES` (
  `COMMIT_HISTORY_ID` bigint PRIMARY KEY,
  `ANALYSIS_ISSUE_LOCATION_ID` bigint NOT NULL,
  `PUSH_HISTORY_ID` bigint,
  `COMMIT_SHA` varchar(255) UNIQUE NOT NULL,
  `COMMIT_MESSAGE` varchar(255) NOT NULL,
  `BRANCH_NAME` varchar(255) NOT NULL,
  `STATUS` varchar(255) NOT NULL COMMENT 'SUCCESS, FAIL',
  `CREATED_AT` datetime,
  `UPDATED_AT` datetime
);

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE `REPOSITORIES` ADD FOREIGN KEY (`GITHUB_ID`) REFERENCES `GITHUB_USERS` (`GITHUB_ID`);

ALTER TABLE `ANALYSIS_REQUESTS` ADD FOREIGN KEY (`REPOSITORY_ID`) REFERENCES `REPOSITORIES` (`REPOSITORY_ID`);

ALTER TABLE `ANALYSIS_RESULTS` ADD FOREIGN KEY (`ANALYSIS_REQUEST_ID`) REFERENCES `ANALYSIS_REQUESTS` (`ANALYSIS_REQUEST_ID`);

ALTER TABLE `ANALYSIS_ISSUES` ADD FOREIGN KEY (`ANALYSIS_RESULT_ID`) REFERENCES `ANALYSIS_RESULTS` (`ANALYSIS_RESULT_ID`);

ALTER TABLE `ANALYSIS_ISSUES_LOCATIONS` ADD FOREIGN KEY (`ANALYSIS_ISSUE_ID`) REFERENCES `ANALYSIS_ISSUES` (`ANALYSIS_ISSUE_ID`);

ALTER TABLE `CHAT_MESSAGES` ADD FOREIGN KEY (`ANALYSIS_REQUEST_ID`) REFERENCES `ANALYSIS_REQUESTS` (`ANALYSIS_REQUEST_ID`);

ALTER TABLE `CHAT_CONTEXTS` ADD FOREIGN KEY (`ANALYSIS_REQUEST_ID`) REFERENCES `ANALYSIS_REQUESTS` (`ANALYSIS_REQUEST_ID`);

ALTER TABLE `CHAT_CONTEXTS` ADD FOREIGN KEY (`CURRENT_ANALYSIS_ISSUE_LOCATION_ID`) REFERENCES `ANALYSIS_ISSUES_LOCATIONS` (`ANALYSIS_ISSUE_LOCATION_ID`);

ALTER TABLE `PUSH_HISTORIES` ADD FOREIGN KEY (`REPOSITORY_ID`) REFERENCES `REPOSITORIES` (`REPOSITORY_ID`);

ALTER TABLE `COMMIT_HISTORIES` ADD FOREIGN KEY (`ANALYSIS_ISSUE_LOCATION_ID`) REFERENCES `ANALYSIS_ISSUES_LOCATIONS` (`ANALYSIS_ISSUE_LOCATION_ID`);

ALTER TABLE `COMMIT_HISTORIES` ADD FOREIGN KEY (`PUSH_HISTORY_ID`) REFERENCES `PUSH_HISTORIES` (`PUSH_HISTORY_ID`);

SET FOREIGN_KEY_CHECKS = 1;